### ISSUE TITLE
CLA does not process my pull request

### ISSUE THREAD

**Issue by dfernandes-egoi** [googledatastudio/ds-data-registry#368]
Even though I submitted correctly and have done all the CLA steps, the bot does not process my pull request. I am in the contributor group, and done all steps correctly.

My PR is #367

**Comment by adamhenson** [comment]
I wonder if the issue is in your `git` user configuration. The error says `Need a CLA for one or more commit authors`.

Looks like you opened the PR as `dfernandes-egoi` user but [the commit](https://github.com/googledatastudio/ds-data-registry/pull/367/commits) is showing `dfernandesegoi` as the user.

Maybe try [configuring your git username](https://help.github.com/en/github/using-git/setting-your-username-in-git) to be `dfernandes-egoi`, configure the matching email if you haven't, and push up an empty commit.

**Comment by pfrisella** [comment]
i added a comment on the PR. Double-check the email addresses associated with the commits.
